#!/bin/sh
#
#	puppet-agent-health-report
#
#	suitable for cron	
#
PATH='/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin'
BAS=`basename $0`
#
#	want a place to cache persistent state, 
# 	so don't make if we have one, and use the same 
#	one durably
HASTEMP=`find /tmp -type d -name "${BAS}" | grep -c "${BAS}"`
[ 0${HASTEMP} -lt 01 ] && {
	TEMP_PATH=$(mktemp -d --tmpdir ${BAS}.XXXXXXXXXX)
	}
TEMP_PATH=`find /tmp -type d -name "${BAS}" | sort | tail -1 `
[ "x${TEMP_PATH}" = "x" ] && {
	echo "error: cannot see a working TEMP_PATH for ${BAS} " 1>&2
	echo " ... bailing" 1>&2
	exit 1
	}
#
RECIPIENTS="licquia@linuxfoundation.org,herrold@owlriver.com"
#
#
STALE_TIME="125"
YMDH=`date +%Y+m%d%H`
PRIORFILE=`find $TEMP_PATH -type f -name "report*"| sort | tail -1`
CURRFILE="$TEMP_PATH/report-${YMDH}"
#
#	for continuity purposes, chirp once a day
ALIVE=15
POSTALIVE=18
HOUR=`date +%H`
[ 0${HOUR} -ge 0${ALIVE} -a 0${HOUR} -lt 0${POSTALIVE} ] && {
	export CONTINUITY="y"
	}
#
RPT_ROOT="/var/lib/puppet/yaml/node"
#
cd ${RPT_ROOT}

find . -mmin +${STALE_TIME} -type f -print \
  | sort \
  | (while read f; do ls -l $f; done) \
  | cut -d' ' -f6- \
  > ${CURRFILE}
#
#	now diff vs last seen to spot changes
OLDMD5=`md5sum ${PRIORFILE} | awk {'print $1'} `
CURRMD5=`md5sum ${CURRFILE} | awk {'print $1'} `

DIRTY=""
[ "x${OLDMD5}" != "x${CURRMD5}" -a -s ${CURRFILE} ] && {
	export DIRTY="y"
	}
[ "x${CONTINUITY}" != "x" ] && {
	export DIRTY="y"
	}
	
if [ "x${DIRTY}" != "x" ]; then
  ( echo    "report:      $BAS" ; \
    echo -n "puppet host: " ;  \
    hostname ; \
    echo -n "date:        " ; \
    date ; \
    echo    "continuity:  ${CONTINUITY}" ; \
    echo    "directory:   ${RPT_ROOT} " ; \
    sed -e 's@./@@g' < $CURRFILE ; \
    echo -n "lines: " ; \
    wc -l $CURRFILE ; \
    echo "# EOJ" ) | \
  mail -s "LSB Puppet agent health ${YYMDH} " \
    ${RECIPIENTS}
fi

cd $TEMP_PATH
# -cmin is in units of minutes -- toss old files
find $TEMP_PATH -cmin $STALE_TIME -type f -a -exec rm {} \;
#
