#!/bin/sh -e
#
# populate the "betaspecs" website area with FHS, LSB specs
#
# TODO (see bug 3344) - need an index page for the top level
# betaspecs should be exported by specific revision (probably tag)
# snapshot specs can just be current head

if [ -d /srv/www/vhosts/linuxbase.org ]; then
    BETASPECS_PATH=/srv/www/vhosts/linuxbase.org/betaspecs
else
    BETASPECS_PATH=/tmp/betaspecs_path
fi

BRANCHURL=http://bzr.linuxfoundation.org/lsb/devel

BZR_PROGRESS_BAR=none
export BZR_PROGRESS_BAR

# obtain the current FHS spec from bzr

[ -d /tmp/fhs-spec ] && rm -rf /tmp/fhs-spec
bzr export /tmp/fhs-spec $BRANCHURL/fhs-spec

# built specs are not in bzr, have to build them here

cd /tmp/fhs-spec
make -s fhs.txt fhs.html 
make -s fhs/index.html 2>/dev/null

[ -d $BETASPECS_PATH/fhs ] && rm -rf $BETASPECS_PATH/fhs
mkdir -p $BETASPECS_PATH/fhs
cp -a fhs.txt fhs.html fhs $BETASPECS_PATH/fhs

cat  > $BETASPECS_PATH/fhs/index.html <<EOF
<html>
<head>
<title>FHS Beta Specification</title>
</head>
<body>
<h1>Filesystem Hierarchy Specification - Beta</h1>
<ul>
<li><a href="fhs.txt">UTF-8 Text</a></li>
<li><a href="fhs.html">HTML (one page)</a></li>
<li><a href="fhs/index.html">HTML (multiple pages)</a></li>
</ul>
</body>
</html>
EOF

cd /tmp
rm -rf fhs-spec

# LSB specs are already built. Grab them from booksets and books branches,
# but only the directories that begin with LSB- are "published"

for branch in $BRANCHURL/booksets $BRANCHURL/books
do
    for path in $(bzr ls $branch)
    do
	book=$(echo $path | sed "s,$branch/,,")
	if [ $(echo $book | grep "^LSB-" | wc -l) -ne 0 ]
	then
	    [ -d $BETASPECS_PATH/lsb/$book ] && rm -rf $BETASPECS_PATH/lsb/$book
	    mkdir -p $BETASPECS_PATH/lsb/$book
	    bzr export $BETASPECS_PATH/lsb/$book $path
	fi
    done
done
