#!/bin/sh -e

if [ "$1" = "--beta" ]; then
    SDK_TYPE=beta
else
    SDK_TYPE=released
fi

if [ -e /tmp/last_installed_sdk ]; then
    if [ $(cat /tmp/last_installed_sdk) = "$SDK_TYPE" ]; then
	echo "$SDK_TYPE SDK already installed"
	exit 0
    fi
fi

rm -f /tmp/last_installed_sdk

mkdir -p /tmp/sdk-install
[ -e $HOME/lsb-$SDK_TYPE-sdk.tar.gz ]

# SDK packages besides lsb-build-base, which has to be handled specially.
SDK_PKGS="lsb-build-cc lsb-build-c++ lsb-build-desktop lsb-build-qt3 lsb-build-qt4 lsb-makelsbpkg"

for pkg in $SDK_PKGS; do
  sudo rpm --nodeps --allmatches -e $pkg || true
done
sudo rpm --nodeps --allmatches -e lsb-build-libbat || true
sudo rpm --nodeps --allmatches -e lsb-build-base || true

(cd /tmp/sdk-install && zcat $HOME/lsb-$SDK_TYPE-sdk.tar.gz | tar xf -)

set +e
rpm -q lsb-setup > /dev/null 2>&1
retval=$?
set -e
if [ $retval -ne 0 ]; then
  sudo rpm -Uvh --force /tmp/sdk-install/lsb-sdk/lsb-setup*rpm
fi

sudo rpm -Uvh --force /tmp/sdk-install/lsb-sdk/lsb-build-base*
for pkg in $SDK_PKGS; do
  sudo rpm -Uvh --force /tmp/sdk-install/lsb-sdk/$pkg*
done

rm -rf /tmp/sdk-install
echo $SDK_TYPE > /tmp/last_installed_sdk
