#!/bin/sh -e

if [ $(whoami) != "buildbot" ]; then
    echo "reset-sdk: run as the buildbot user" >&2
    exit 1
fi

if [ -e /tmp/last_installed_sdk ]; then
    if [ $(cat /tmp/last_installed_sdk) = "devel" ]; then
	echo "devel SDK already installed:"
        # use --version instead of --lsbcc-version to get gcc version also
	/opt/lsb/bin/lsbcc --version
	/opt/lsb/bin/lsbcc --lsb-version
	echo -n "Distribution "
	lsb_release -d
	exit 0
    fi
fi

rm -f /tmp/last_installed_sdk

if [ \! -e ../../saved/devel/sdk.tar.gz ]; then
    echo "could not find devel SDK to install" >&2
    exit 1
fi

rm -rf /tmp/install-sdk
mkdir /tmp/install-sdk
zcat ../../saved/devel/sdk.tar.gz | (cd /tmp/install-sdk && tar xf -)

find /tmp/install-sdk -name \*.rpm -print | grep -v src.rpm | \
  xargs sudo rpm -Uvh --force

rm -rf /tmp/install-sdk

echo "devel" > /tmp/last_installed_sdk

echo "SDK updated to devel:"
# use --version instead of --lsbcc-version to get gcc version also
/opt/lsb/bin/lsbcc --version
/opt/lsb/bin/lsbcc --lsb-version
echo -n "Distribution "
lsb_release -d
